version: '3.7'
services:
  rpc-server:
    build: .
    ports:
      - "3355:3355"
    # volumes:
    #   - ./docker_db:/usr/src/app/file_db
    networks:
      - default
      - lakat-backend

  # flask-service:
  #   build: ./http-server
  #   ports:
  #     - "3356:3000"
  #   depends_on:
  #     - rpc-server

networks:
  lakat-backend:
    name: lakat-backend
