# BUCKET SCHEMAS
DEFAULT_ATOMIC_BUCKET_SCHEMA = '1'
DEFAULT_MOLECULAR_BUCKET_SCHEMA = '2'
DEFAULT_PULLREQUEST_BUCKET_SCHEMA = '3'
DEFAULT_REGISTRY_BUCKET_SCHEMA = '4'
DEFAULT_NAME_RESOLUTION_BUCKET_SCHEMA = '5'

# BUCKET ID TYPES
BUCKET_ID_TYPE_NO_REF = 0
BUCKET_ID_TYPE_WITH_ID_REF = 1