ALGORITHM = 'sha2-256'
ALG_POSSIBLE= ['sha1', 'sha2-256', 'sha2-512']
ENCODING_FUNCTION = 'utf-8'
MH_BRANCHID_PREFIX_LENGTH = 8
DEV_HASH_LENGTH = 8
DEFAULT_CODEC = 0x51
DEFAULT_SUFFIX_CROP = 4
DEV_SUFFIX_CROP = 2