## TRIE RESPONSES
TRIE_SUCCESS_CODE = 200
TRIE_ERROR_CODE_NODE_DOES_NOT_EXIST_IN_DB = 300
TRIE_ERROR_CODE_NODE_DOES_NOT_HAVE_THIS_CHILD = 500
TRIE_ERROR_CODE_NODE_DOES_NOT_EXIST = 400

## ARTICLE RESPONSES
ARTICLE_FOUND_RESPONSE_CODE = 200
ARTICLE_NOT_FOUND_TRIE_LOOKUP_ERROR = 300
ARTICLE_NOT_FOUND_RESPONSE_CODE = 404
ARTICLE_NOT_FOUND_DB_RESPONSE_BAD = 500