from config.db_cfg import NUMBER_OF_SUFFIXLESS_NAMESPACES

BRANCH_NS=0
ATOMIC_BUCKET_NS=1
MOLECULAR_BUCKET_NS=2

## NUMBER_OF_SUFFIXLESS_NAMESPACES=10
BRANCH_HEAD_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES
DATA_TRIE_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 1
CONFIG_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 2
SUBMIT_NS= NUMBER_OF_SUFFIXLESS_NAMESPACES + 3
SUBMIT_TRACE_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 4
TOKEN_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 5
NAME_RESOLUTION_TRIE_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 6
INTERACTION_TRIE_NS=NUMBER_OF_SUFFIXLESS_NAMESPACES + 7
