BRANCH_NS=0
ATOMIC_BUCKET_NS=1
MOLECULAR_BUCKET_NS=2

## NUMBER_OF_SUFFIXLESS_NAMESPACES=10

BRANCH_HEAD_NS=10
DATA_TRIE_NS=11
CONFIG_NS=12
SUBMIT_NS=13
SUBMIT_TRACE_NS=14
TOKEN_NS=15
NAME_RESOLUTION_NS=16
NAME_RESOLUTION_TRIE_NS=17
INTERACTION_TRIE_NS=18
